version: 6.0.0.{build}
skip_tags: true
image: Visual Studio 2017
build_script:
- ps: .\Build\Build-Release.ps1 $env:APPVEYOR_BUILD_VERSION '' 1
artifacts:
- path: build\Releases\v$(APPVEYOR_BUILD_VERSION)\*.nupkg
  name: Nuget Package