version: 6.0.0
skip_non_tags: true
image: Visual Studio 2017
build_script:
- ps: .\Build\Build-Release.ps1 $env:APPVEYOR_BUILD_VERSION '' 1
artifacts:
- path: build\Release\*.nupkg
  name: Nuget Package
deploy:
- provider: NuGet
  api_key:
    secure: bUbD7nXHxmrIWR1bP+pVv1fhPYZlI4JEn9jZMYsz8l5VFVeqkiuMMOQ97xT72q7H
  on:
    branch: master